# -*- coding: utf-8 -*-
"""Final_Medium_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQWxWc8wyqY_rMD66nhxJjAbRSesyfXD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

movies = pd.read_csv("/content/sample_data/imdb_top_1000.csv")
print("Dataset Shape:", movies.shape)
print("\nColumns:")
print(movies.columns.tolist())

cols_needed = [
    "Series_Title",
    "Genre",
    "IMDB_Rating",
    "Runtime",
    "No_of_Votes",
    "Released_Year"
]

movies = movies[cols_needed].copy()

movies["Runtime"] = pd.to_numeric(
    movies["Runtime"].astype(str).str.replace(
        " min",
        "",
        regex=False
    ),
    errors="coerce"
)

movies["Released_Year"] = pd.to_numeric(
    movies["Released_Year"],
    errors="coerce"
)

movies["IMDB_Rating"] = pd.to_numeric(
    movies["IMDB_Rating"],
    errors="coerce"
)

movies["No_of_Votes"] = pd.to_numeric(
    movies["No_of_Votes"],
    errors="coerce"
)

numeric_cols = [
    "IMDB_Rating",
    "Runtime",
    "No_of_Votes",
    "Released_Year"
]

for col in numeric_cols:
    movies[col] = movies[col].fillna(
        movies[col].median()
    )

movies["Genre"] = movies["Genre"].fillna(
    "Unknown"
).astype(str)

movies["No_of_Votes"] = np.log1p(
    movies["No_of_Votes"]
)

print("\nMissing Values After Cleaning:")
print(movies.isna().sum())

genre_dummies = movies["Genre"].str.get_dummies(
    sep=","
)

genre_dummies.columns = [
    col.strip()
    for col in genre_dummies.columns
]

X = pd.concat([
    movies[[
        "IMDB_Rating",
        "Runtime",
        "No_of_Votes",
        "Released_Year"
    ]],
    genre_dummies
], axis=1)

print("\nFeature Matrix Shape:", X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nScaled Feature Matrix Shape:")
print(X_scaled.shape)

k_values = range(2, 10)

inertias = []
sil_scores = []

for k in k_values:

    km = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = km.fit_predict(X_scaled)

    inertias.append(
        km.inertia_
    )

    sil_scores.append(
        silhouette_score(
            X_scaled,
            labels
        )
    )

print("k_values:", list(k_values))
print("inertias:", inertias)
print("silhouette scores:", sil_scores)

plt.figure(figsize=(8, 5))

plt.plot(
    list(k_values),
    inertias,
    marker="o"
)

plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")

plt.title("Elbow Method for Optimal k")

plt.grid(True)

plt.savefig(
    "elbow_method_actual.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

plt.figure(figsize=(8, 5))

plt.plot(
    list(k_values),
    sil_scores,
    marker="o"
)

plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")

plt.title(
    "Silhouette Scores for Different k Values"
)

plt.grid(True)

plt.savefig(
    "silhouette_scores_actual.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

movies.head(10).to_csv("dataset_preview.csv", index=False)

best_k = list(k_values)[
 np.argmax(sil_scores)
]
print(
 "\nBest k based on silhouette score:",
 best_k
)

k=4

kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

movies["cluster"] = kmeans.fit_predict(X_scaled)

print(movies["cluster"].value_counts())
for cluster_id in sorted(movies["cluster"].unique()):

    print(f"\nCluster [{cluster_id}]")

    example_movies = movies[
        movies["cluster"] == cluster_id
    ][[
        "Series_Title",
        "Genre",
        "IMDB_Rating",
        "Runtime",
        "No_of_Votes",
        "Released_Year"
    ]].head(5)

    print(example_movies.to_string(index=False))

cluster_summary = movies.groupby(
    "cluster"
)[numeric_cols].agg([
    "mean",
    "median",
    "count"
])

print("\nCluster Summary:")
print(cluster_summary)

for cluster_id in sorted(movies["cluster"].unique()):
    print(f"\nCluster [{cluster_id}]")
    example_movies = movies[
        movies["cluster"] == cluster_id
    ][[
        "Series_Title",
        "Genre",
        "IMDB_Rating",
        "Runtime",
        "No_of_Votes",
        "Released_Year"
    ]].head(5)
    print(example_movies.to_string(index=False))

print("\nAnalysis Completed Successfully.")